const trendList = [
  {
    label: "Home",
    key: 1
  },
  {
    label: "Trend",
    key: 2
  },
  {
    label: "Trend Details",
    key: 3
  },
  {
    label: "Start to Generate",
    key: 4
  }
]
const designList = [
  {
    label: "Home",
    key: 1
  },
  {
    label: "Start to Generate",
    key: 2
  },
  {
    label: "Generating",
    key: 3
  },
  {
    label: "Showcase",
    key: 4
  }
]

const navList = [
  {
    label: "Trend",
    width: 80,
    left: 2
  },
  {
    label: "Design",
    width: 87,
    left: 88
  },
  {
    label: "Supply Chain",
    width: 132,
    left: 181 // 这里向左偏移2像素 留出间距
  }
]

const supplyChainList = [
  {
    title: "Project Planning",
    content:
      "Send your tech pack or pic of the design you want. We will assist you in verifying your materials and fitting details. The advice about sample fee, MOQ and estimate bulk price.",
    key: 1
  },
  {
    title: "Sourcing Materials",
    content:
      "We work with local suppliers to acquire high-quality materials and assure that we stay below your specified price points. Lead times may be significantly shortened by choosing in-stock products.",
    key: 2
  },
  {
    title: "Pattern Making",
    content:
      "Work with our expert pattern makers to achieve the features and fit of each style. Patterns are essentially the blueprint for all clothing items.",
    key: 3
  },
  {
    title: "Sample Making",
    content:
      "Our skilled sample makers hand cut and sew your garments with detail and precision. By creating samples of your clothing, we're able to test the fit and functionality before mass production.",
    key: 4
  },
  {
    title: "Revisions",
    content:
      "We provide a sample fitting to identify necessary changes for your next batch. Thanks to our experienced team, we complete all revisions in just 1–2 rounds, whereas traditional manufacturers may require 5+ rounds.",
    key: 5
  },
  {
    title: "Productions",
    content:
      "With your sample approved, we can begin pre-production. Placing your purchase order will initiate your first production run.",
    key: 6
  }
]

const messageList = [
  {
    key: "Trend",
    img: "Trend_text.png",
    value:
      "With its acute data perception ability and in-depth analysis ability, it accurately captures the subtle changes of the fashion trend vane, providing important insights for brands to make forward-looking layouts."
  },
  {
    key: "Design",
    img: "Design_text.png",
    value:
      "Our designs are generated by artificial intelligence based on brand styles combined with fashion trend data, enabling brand owners and buyers to design and choose original styles more freely and also providing marketing materials."
  },
  {
    key: "Supply Chain",
    img: "Supply_Chain_text.png",
    value:
      "With the assistance of an expert team that has 20 years of experience in clothing development for review, we reduce the rate of wasted patterns and time costs, and achieve the on-site development of sample garments in a one-stop manner."
  }
]

export { navList, trendList, designList, supplyChainList, messageList }
